config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => { registrations: 'admin/registrations' }
  devise_for :users, :controllers => { registrations: 'creator/registrations' }
  
  get 'welcome/index'
  root 'welcome#index'

  namespace :admin do
    root to: 'dashboard#index'

    resource :dashboard
    resources :users
    resources :admins
    resources :orders
    resources :colors
    resources :collections
    resources :color_positions
    resources :bracelets do
      collection do
        get 'pallete'
        get 'change'
        get 'changerow'
        get 'changeentiretable'
      end
    end
  end

  namespace :creator do
    get 'order_items/create'
    get 'order_items/update'
    get 'order_items/destroy'
    get 'carts/show'
    post 'orders/change_order_status'
    resources :users
    resources :orders do
      collection do
        get 'show_shipping_address'
        get 'edit_shipping_address'
      end
    end
    resources :order_status
    resources :collections
    resources :colors, only: [:show, :index]
    resources :color_positions
    resources :order_items, only: [:create, :update, :destroy] do
      collection do
        get 'cart_row'
        get 'shopping_cart'
      end
    end
    resources :bracelets do
      member do
        get 'copy'
      end
      collection do
        get 'update_sum_price'
        get 'pallete'
        get 'change'
        get 'changerow'
        get 'changeentiretable'
        get 'draft_list'
      end
    end
  end

    

end

app/controllers/admin/bracelets_controller.rb
class Admin::BraceletsController < Admin::AdminController
  before_action :set_bracelet, only: [:show, :edit, :update, :destroy, :changerow, :changeentiretable]
  before_action :set_current_color, only: [:pallete, :edit, :change, :changerow, :changeentiretable]
  before_action :set_color_position, only: [:change]
  # GET /bracelets
  # GET /bracelets.json
  
  
  def index
    @bracelets = Bracelet.all
  end

  # GET /bracelets/1
  # GET /bracelets/1.json
  def show
    @color_positions = @bracelet.color_positions
    @colors = @bracelet.colors.uniq
  end

  # GET /bracelets/new 
  def new
    @bracelet = Bracelet.new
  end

  def pallete
    @colors = Color.available
  end

  def change
    @color_position.color = @current_color
    @color_position.save!
  end

  def changerow
    @row_index = params[:row_idx].to_i
    
    @color_positions = @bracelet.positions_in_first_look_for_iteration(@row_index)
    
    @color_positions.each do |color_position|
      color_position.color = @current_color
      color_position.save
    end
  end
  
  def changeentiretable
    @bracelet.color_positions.each do |cp|
      cp.color = @current_color
      cp.save
    end
  end
  
  # GET /bracelets/1/edit
  
  def edit
    @colors = Color.all
  end

  # POST /bracelets
  # POST /bracelets.json
  
  def create
    @users = User.all
    @bracelet = Bracelet.new(bracelet_params)
    respond_to do |format|
      if @bracelet.save
        format.html { redirect_to edit_admin_bracelet_path(@bracelet), notice: 'Bracelet was successfully created.' }
        format.json { render :edit, status: :created, location: admin_bracelet_path(@bracelet) }
      else
        format.html { render :new }
        format.json { render json: admin_bracelet_path(@bracelet).errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bracelets/1
  # PATCH/PUT /bracelets/1.json
  
  def update
    if @bracelet.colors.uniq.count > 7
      redirect_to edit_creator_bracelet_path(@bracelet), notice: 'Użyłeś za dużo kolorów. Maksymalna ilość kolorów w bransoletce to 7'
      return
    end
      respond_to do |format|
        if @bracelet.update(bracelet_params)
          format.html { redirect_to admin_bracelet_path(@bracelet), notice: 'Bracelet was successfully updated.' }
          format.json { render :show, status: :ok, location: admin_bracelet_path(@bracelet) }
        else
          format.html { render :edit }
          format.json { render json: admin_bracelet_path(@bracelet).errors, status: :unprocessable_entity }
        end
      end
    end

  # DELETE /bracelets/1
  # DELETE /bracelets/1.json
  def destroy
    @bracelet.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Bracelet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_color_position
      @color_position = ColorPosition.find(params[:position_id])
    end

    def set_current_color
      @current_color = Color.find_by_hex(params[:current_color].upcase) if params[:current_color]
      
      if !@current_color
          @current_color = Color.first
      end
    end

    def set_bracelet
      @bracelet = Bracelet.includes(:color_positions => [:color]).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bracelet_params
      params.require(:bracelet).permit(:clasp, :casp, :color_position_id, :row_count, :price, :height, :draft, :collection_id)
    end
end

app/controllers/bracelets_controller.rb
class BraceletsController < ApplicationController
  before_action :set_bracelet, only: [:show, :edit, :update, :destroy]
  before_action :set_current_color, only: [:pallete, :edit, :change]
  before_action :set_color_position, only: [:change]
  # GET /bracelets
  # GET /bracelets.json
  
  
  def index
    @bracelets = Bracelet.all
  end

  # GET /bracelets/1
  # GET /bracelets/1.json
  def show
  end

  # GET /bracelets/new
  def new
    @bracelet = Bracelet.new
  end

  def pallete
    @colors = Color.all
  end

  def change
    @color_position.color = @current_color
    @color_position.save!
  end

  # GET /bracelets/1/edit
  def edit
    @colors = Color.all
  end

  # POST /bracelets
  # POST /bracelets.json
  def create
    @bracelet = Bracelet.new(bracelet_params)
    respond_to do |format|
      if @bracelet.save
        format.html { redirect_to edit_bracelet_path(@bracelet), notice: 'Bracelet was successfully created.' }
        format.json { render :edit, status: :created, location: @bracelet }
      else
        format.html { render :new }
        format.json { render json: @bracelet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bracelets/1
  # PATCH/PUT /bracelets/1.json
  def update
    respond_to do |format|
      if @bracelet.update(bracelet_params)
        format.html { redirect_to @bracelet, notice: 'Bracelet was successfully updated.' }
        format.json { render :show, status: :ok, location: @bracelet }
      else
        format.html { render :edit }
        format.json { render json: @bracelet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bracelets/1
  # DELETE /bracelets/1.json
  def destroy
    @bracelet.destroy
    respond_to do |format|
      format.html { redirect_to bracelets_url, notice: 'Bracelet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_color_position
      @color_position = ColorPosition.find(params[:position_id])
    end

    def set_current_color
      @current_color = Color.find_by_hex(params[:current_color].upcase) if params[:current_color]
      
      if !@current_color
          @current_color = Color.first
      end

    end

    def set_bracelet
      @bracelet = Bracelet.includes(:color_positions).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bracelet_params
      params.require(:bracelet).permit(:clasp, :casp, :color_position_id, :row_count, :price, :height)
    end
end

app/controllers/creator/bracelets_controller.rb
class Creator::BraceletsController < Creator::CreatorController
  before_action :set_bracelet, only: [:show, :edit, :update, :destroy, :changerow, :changeentiretable]
  before_action :set_current_color, only: [:pallete, :edit, :change, :changerow, :changeentiretable, :copy]
  before_action :set_color_position, only: [:change]
  # GET /bracelets
  # GET /bracelets.json
  
  
  def index
    @bracelets = Bracelet.where(collection_id: current_user.collection.id)
    @order_item = current_order.order_items.new
  end
  
  # GET /bracelets/1
  # GET /bracelets/1.json
  def show
    @colors = @bracelet.colors.uniq
  end
  
  def copy
    @colors = Color.available
    @old_bracelet = Bracelet.find(params[:id])
    @bracelet = @old_bracelet.deep_clone include: :color_positions
    @bracelet.collection = Collection.find_by(user_id: current_user.id)
    @bracelet.save!
    render 'edit'
  end

  # GET /bracelets/new
  def new
    @bracelet = Bracelet.new
  end

  def pallete
    @colors = Color.available
  end

  def change
    @color_position.color = @current_color
    @color_position.save!
  end

  def changerow

    @row_index = params[:row_idx].to_i
    
    @color_positions = @bracelet.positions_in_first_look_for_iteration(@row_index)
    
    @color_positions.each do |color_position|
      color_position.color = @current_color
      color_position.save
    end

  end
  
  def changeentiretable
    
    @bracelet.color_positions.each do |cp|
      cp.color = @current_color
      cp.save
    end
    
  end
  def update_sum_price
    @bracelet = Bracelet.find(params[:bracelet_id])
  end
  # GET /bracelets/1/edit
  def edit
    @colors = Color.available
  end

  # POST /bracelets
  # POST /bracelets.json
  def create
    params[:bracelet][:user_id]= current_user.id   
    @bracelet = Bracelet.new(bracelet_params)
    respond_to do |format|
      if @bracelet.save
        format.html { redirect_to edit_creator_bracelet_path(@bracelet), notice: 'Bracelet was successfully created.' }
        format.json { render :edit, status: :created, location: creator_bracelet_path(@bracelet) }
      else
        format.html { render :new }
        format.json { render json: creator_bracelet_path(@bracelet).errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bracelets/1
  # PATCH/PUT /bracelets/1.json
  def update
      respond_to do |format|
        if @bracelet.update(bracelet_params)
          format.html { redirect_to creator_bracelet_path(@bracelet), notice: 'Bracelet was successfully updated.' }
          format.json { render :show, status: :ok, location: admin_bracelet_path(@bracelet) }
        else
          format.html { render :edit }
          format.json { render json: creator_bracelet_path(@bracelet).errors, status: :unprocessable_entity }
        end
      end
  end

  # DELETE /bracelets/1
  # DELETE /bracelets/1.json
  def destroy
    @bracelet.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Bracelet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_color_position
      @color_position = ColorPosition.find(params[:position_id])
    end

    def set_current_color
      @current_color = Color.find_by_hex(params[:current_color].upcase) if params[:current_color]
      
      if !@current_color
          @current_color = Color.first
      end

    end

    def set_bracelet
      @bracelet = Bracelet.includes(:color_positions => [:color]).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bracelet_params
      params.require(:bracelet).permit(:clasp, :casp, :color_position_id, :row_count, :price, :height, :draft, :collection_id)
    end
end

app/controllers/creator/carts_controller.rb
class Creator::CartsController < Creator::CreatorController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/creator/collections_controller.rb
class  Creator::CollectionsController < Creator::CreatorController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @public_collections = Collection.where(public: true)
    @my_collection = Collection.where(user_id: current_user)
    @collections = @public_collections.to_a + @my_collection.to_a
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @bracelets = @collection.bracelets
    @order_item = current_order.order_items.new
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end


  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:user_id)
    end
end

app/controllers/creator/color_positions_controller.rb
class Creator::ColorPositionsController < Creator::CreatorController
  before_action :set_color_position, only: [:show, :edit, :update, :destroy]
  
  # GET /color_positions
  # GET /color_positions.json
  def index
    @color_positions = ColorPosition.all
  end

  # GET /color_positions/1
  # GET /color_positions/1.json
  def show
  end

  # GET /color_positions/new
  def new
    @color_position = ColorPosition.new
  end

  # GET /color_positions/1/edit
  def edit
  end

  # POST /color_positions
  # POST /color_positions.json
  def create
    @color_position = ColorPosition.new(color_position_params)

    respond_to do |format|
      if @color_position.save
        format.html { redirect_to creator_color_position_path(@color_position), notice: 'Color position was successfully created.' }
        format.json { render :show, status: :created, location: creator_color_position_path(@color_position)}
      else
        format.html { render :new }
        format.json { render json: creator_color_position_path(@color_position).errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /color_positions/1
  # PATCH/PUT /color_positions/1.json
  def update
    respond_to do |format|
      if @color_position.update(color_position_params)
        format.html { redirect_to creator_color_position_path(@color_position), notice: 'Color position was successfully updated.' }
        format.json { render :show, status: :ok, location: creator_color_position_path(@color_position) }
      else
        format.html { render :edit }
        format.json { render json: creator_color_position_path(@color_position).errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /color_positions/1
  # DELETE /color_positions/1.json
  def destroy
    @color_position.destroy
    respond_to do |format|
      format.html { redirect_to creator_color_positions_url, notice: 'Color position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color_position
      @color_position = ColorPosition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def color_position_params
      params.require(:color_position).permit(:color_id, :position, :bracelet_id)
    end
end

app/controllers/creator/creator_controller.rb
class Creator::CreatorController < ApplicationController
    before_action :authorize

    def authorize
      if !current_user
        redirect_to new_user_session_path
        return
      end
    end
end

app/controllers/creator/order_items_controller.rb
class Creator::OrderItemsController < Creator::CreatorController
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end
  def order_item_params
      params.require(:order_item).permit(:quantity, :bracelet_id, :unit_price, :order_id, :total_price)
  end
end

app/helpers/bracelets_helper.rb
module BraceletsHelper
end

app/views/creator/bracelets/_editform.html.haml
= simple_form_for [:creator, @bracelet] do |f|
  = notice
  - if @bracelet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bracelet.errors.count, "error")} prohibited this bracelet from being saved:"
      %ul
        - @bracelet.errors.full_messages.each do |msg|
          %li= msg
  .recnt
    .container
      .col-md-9
        .box
          %h3 Stwórz wzór bransoletki i dobierz wykończenie.
          .boxp
            Wybierz kolor oraz zapełnij całą bransoletkę klikając na przycisk "wypełnij" (może to potrwać chwilę), możesz również wypełniać poszczególne wiersze klikając na ikonki lub wypełniać poszczególne komórki klikając na komórki. Po stworzeniu wzoru dobierz końcówki oraz zapięcie. W każdej chwili możesz przeliczyć cenę i sprawdzić ile kosztuje Twój projekt. Więcej informacji na temat cen znajdziesz w zakładce "Ceny".
        .box2
          %i.znak{style:'float:left'}
          %i.ptaszek
          Potrzebujesz pomocy? Zobacz jak korzystać z kreatora bransoletek
          %i.ptaszek
          %i.znak{style:'float:right'}
        .box4
          %i.jedynka{style:'float:left'}
          %table
            %tr
              %td{class: "fill-entire_table", style:'width:150px',onclick:"fillTable(#{@bracelet.id})"}
                %center
                  = "wypełnij"
          = render 'first_throw'
          .tools{style:'margin-left:15px;display:table;float:left'}
            - a = @bracelet.rows_for_first_throw
            - (0..a).each do |row_index|
              %table
                %tr
                  %td{class: "fill-row-#{row_index}", style:'background-image:url("/assets/stock_bucketfill.png");background-size:cover', onclick:"fillRow(#{row_index}, #{@bracelet.id})"}
          = render 'second_throw'
      .col-md-3a{style:'margin-left:10px'}
        .box3
          %i.dwa
          %br
          .field
            A. Zmiana grubości i długości bransoletki
            %br
            %br
            Jeśli chcesz zmienić długość i szerokość bransoletki zrób to zanim stworzysz wzór! Jeśli się cofniesz, wszystkie zmiany z tego widoku nie zostaną zapisane.
            %br
            %br
            %button
              = link_to 'Zmień długość i szerokość bransoletki', new_creator_bracelet_path
            %br
          .field
            A. Wybierz kolor zakończenia
            = f.input :casp, collection: ["Srebrne","Złote","Miedziane"]
          .field
            B. Wybierz rodzaj zapięcia
            = f.input :clasp, collection: ["karabińczyk","toogle"]
          - if @bracelet.find_unavailable_colors.present?
            .field
              C. Niedostępne kolory:
              %br
              - @bracelet.find_unavailable_colors.each do |f|
                %br
                = f
              Jeśli zamówisz bransoletkę z niedostępnym kolorem jej okres realizacji znacznie się wydłuży. O dokładnym czasie realizacji powiadomimy w osobnym mailu. Jeśli nie chcesz czekać, zmień niedostępny kolor na któryś z dostępnych kolorów
  .footer-top{style:'background-color:#f0f0f0;padding:2em'}
    .container
      %i.jedynka{style:'float:left'}
      = render 'pallete' 
      .col-sm-5{style:'float:right'}
        %i.trojka
        %button 
          = link_to "Przelicz cenę", update_sum_price_creator_bracelets_path(bracelet_id: @bracelet), remote:true
        #update_sum_price
          = 'Cena netto'
          = number_to_currency(@bracelet.sum_price)
          = 'Cena brutto'
          = number_to_currency(@bracelet.sum_price * 1.23)
          %br
      
        = 'Twoja początkowa cena dla wybranej długości i szerokości bransoletki to:'
        %br
        = 'Cena brutto'
        = number_to_currency(@bracelet.sum_price * 1.23, :precision => 0)
        %br
        .actions
          = f.submit 'Podsumuj bransoletkę'

app/views/creator/bracelets/_first_throw.html.haml
#entire_table{style:'display:table;float:left'}
  - a = (@bracelet.height * 4.55).ceil
  - (0..a).each do |row_index|
    %table
      = render 'single_row', :@color_positions => @bracelet.positions_in_first_look_for_iteration(row_index).to_a, :@row_index => row_index

app/views/creator/bracelets/index.html.haml
/ %h1 Bransoletki zamówione
/ %table
/   %thead
/     %tr
/       %th Clasp
/       %th Casp
/       %th Row count
/       %th Height
/       %th Price
/       %th order
/       %th
/       %th
/       %th
/     %tbody
/     - @bracelets_with_order.each do |bracelet|
/       %tr
/         %td= bracelet.clasp
/         %td= bracelet.casp
/         %td= bracelet.row_count
/         %td= bracelet.height
/         %td= bracelet.price
/         %td= bracelet.order.id.to_s
/         %td= link_to 'Show', creator_bracelet_path(bracelet)
/         %td= link_to 'Edit', edit_creator_bracelet_path(bracelet)
/         %td= link_to 'Destroy', creator_bracelet_path(bracelet), :method => :delete, :data => { :confirm => 'Are you sure?' }
%h1 Bransoletki niezamówione
%table
  %thead
    %tr
      %th Clasp
      %th Casp
      %th Row count
      %th Height
      %th Price
      %th
      %th
      %th
      %th
    %tbody
    - @bracelets.each do |bracelet|
      %tr
        %td= bracelet.clasp
        %td= bracelet.casp
        %td= bracelet.row_count
        %td= bracelet.height
        %td= number_to_currency bracelet.sum_price
        %td= render "bracelet_row", bracelet: bracelet, order_item: @order_item
        %td= link_to 'Show', creator_bracelet_path(bracelet)
        %td= link_to 'Edit', edit_creator_bracelet_path(bracelet)
        %td= link_to 'Destroy', creator_bracelet_path(bracelet), :method => :delete, :data => { :confirm => 'Are you sure?' }
%br
= link_to 'New Bracelet', new_creator_bracelet_path

app/views/creator/bracelets/new_bracelet.html.haml
= simple_form_for [:creator, @bracelet] do |f|
  = notice
  - if @bracelet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bracelet.errors.count, "error")} prohibited this bracelet from being saved:"
      %ul
        - @bracelet.errors.full_messages.each do |msg|
          %li= msg
  %br
  %br
  = '1. Wybierz kolor'
  %br
  = '2. Wypełnij wszystko klikając na przycisk "wypełnij"(może to potrwać chwilę), wypełnij poszczególne wiersze klikając na ikonki lub wypełnij poszczególne komórki klikając na komórki'
  %br
  = '3. Stwórz swój wzór. Jeśli chcesz powtarzalny schemat na bransoletce wykonaj jeden schemat, resztę wzoru pozostaw białym.'
  %br
  = '4. Obserwuj zmiany na symulatorze bransoletki'
  %br
  = '5. Wybierz końcówki i zapięcie'
  %br
  = '6. Podsumuj swój projekt'
  %br
  %br
  = 'Twoja początkowa cena dla wybranej długości i szerokości bransoletki to:'
  %br
  = 'Cena netto'
  = number_to_currency(@bracelet.sum_price)
  = 'Cena brutto'
  = number_to_currency(@bracelet.sum_price * 1.23)
  %br
  = "Jeśli chcesz zmienić długość i szerokość bransoletki zrób to zanim stworzysz wzór! Jeśli się cofniesz, wszystkie zmiany z tego widoku nie zostaną zapisane."
  = link_to 'Zmień długość i szerokość bransoletki', new_creator_bracelet_path
  %br
  %br
  = render 'pallete' 
  %table
    %tr
      %td{class: "fill-entire_table", style:'width:150px',onclick:"fillTable(#{@bracelet.id})"}
        %center
          = "wypełnij"
  = render 'first_throw'
  .tools{style:'margin-left:15px;display:table;float:left'}
    - a = @bracelet.rows_for_first_throw
    - (0..a).each do |row_index|
      %table
        %tr
          %td{class: "fill-row-#{row_index}", style:'background-image:url("/assets/stock_bucketfill.png");background-size:cover', onclick:"fillRow(#{row_index}, #{@bracelet.id})"}


  = render 'second_throw'
  .field
    = f.input :casp, label: "Wybierz kolor wykończenia bransoletki", collection: ["Srebrne","Złote","Miedziane"]
  .field
    = f.input :clasp, label: "Wybierz zapięcie", collection: ["karabińczyk","toogle"]
  
  %br
  - @bracelet.find_unavailable_colors.each do |f|
    %br
    = f
  %br
  %br
  Jeśli zamówisz bransoletkę z niedostępnym kolorem jej okres realizacji znacznie się wydłuży. O dokładnym czasie realizacji powiadomimy w osobnym mailu. Jeśli nie chcesz czekać, zmień niedostępny kolor na któryś z dostępnych kolorów
  %button 
    = link_to "Przelicz cenę", update_sum_price_creator_bracelets_path(bracelet_id: @bracelet), remote:true
  #update_sum_price
    = 'Cena netto'
    = number_to_currency(@bracelet.sum_price)
    = 'Cena brutto'
    = number_to_currency(@bracelet.sum_price * 1.23)
  %br
  .actions
    = f.submit 'Podsumuj bransoletkę'

app/views/creator/bracelets/show.html.haml
%p#notice= notice
.panel
  Duplikuj
  = link_to "copy", copy_creator_bracelet_path(params[:id])   
  %br
  Zapięcie:
  = @bracelet.clasp
  %br
  Wykończenie:
  = @bracelet.casp
  %br
  Ilość koralików w rzędzie
  = @bracelet.row_count
  %br
  Długość bransoletki (cm)
  = @bracelet.height.to_s + ' cm'
  %br
  Kolory użyte w bransoletce
  %table
    - @colors.each do |color|
      %tr
        %td
          = color.try(:name)
        %td.color-to-select{style:"background-color:##{color.hex}"}
  %br
  = 'Cena netto'
  = number_to_currency(@bracelet.sum_price)
  %br
  %br
  = 'Cena brutto'
  = number_to_currency(@bracelet.sum_price * 1.23)
  %br
  %br
  = link_to 'Edit', edit_creator_bracelet_path(@bracelet)
  \|
  = link_to 'Przejdź do zamówienia', creator_collection_path(current_user.collection)
  %br
  = 'Podgląd wzoru'
  %div{:style => "transform:rotate(90deg); -webkit-transform:rotate(90deg); \r\n-moz-transform:rotate(90deg); -o-transform:rotate(90deg);display: inline-block;margin-left:30%;margin-top:-30%"}
    - a = (@bracelet.height * 4.55).ceil
    - (0..a).each do |row_index|
      %table
        %tr
          - if ((row_index % 2 ) == 0)
            %td.small-no-border
          - @bracelet.positions_in_first_look_for_iteration(row_index).to_a.each do |x|
            %td.small{style:"background-color:##{x.color.hex};"}
              - x.position
  %br
  %div{:style => "transform:rotate(90deg); -webkit-transform:rotate(90deg); \r\n-moz-transform:rotate(90deg); -o-transform:rotate(90deg);display: inline-block;margin-left:40%;margin-top:-50%"}
    - a = (@bracelet.height * 4.55).ceil
    - (0..a).each do |row_index|
      %table
        %tr
          - if ((row_index % 2 ) == 0)
            - can = @bracelet.positions_in_second_look_for_iteration(row_index).to_a.first
          - else
            - can = @bracelet.positions_in_second_look_for_iteration(row_index).to_a.last  
          - @bracelet.positions_in_second_look_for_iteration(row_index).to_a.each do |x|
            - cla = can == x ? 'small_second' : 'normal_second'
            %td{style:"background-color:##{x.color.hex};", class: "#{cla}"}
              - x.position