config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => { registrations: 'admin/registrations' }
  devise_for :users, :controllers => { registrations: 'creator/registrations' }
  
  get 'welcome/index'
  root 'welcome#index'

  namespace :admin do
    root to: 'dashboard#index'

    resource :dashboard
    resources :users
    resources :admins
    resources :orders
    resources :colors
    resources :collections
    resources :color_positions
    resources :bracelets do
      collection do
        get 'pallete'
        get 'change'
        get 'changerow'
        get 'changeentiretable'
      end
    end
  end

  namespace :creator do
    get 'order_items/create'
    get 'order_items/update'
    get 'order_items/destroy'
    get 'carts/show'
    post 'orders/change_order_status'
    resources :users
    resources :orders do
      collection do
        get 'show_shipping_address'
        get 'edit_shipping_address'
      end
    end
    resources :order_status
    resources :collections
    resources :colors, only: [:show, :index]
    resources :color_positions
    resources :order_items, only: [:create, :update, :destroy] do
      collection do
        get 'cart_row'
        get 'shopping_cart'
      end
    end
    resources :bracelets do
      member do
        get 'copy'
      end
      collection do
        get 'update_sum_price'
        get 'pallete'
        get 'change'
        get 'changerow'
        get 'changeentiretable'
        get 'draft_list'
      end
    end
  end

    

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  has_many :bracelets, through: :order_items
  belongs_to :user
  accepts_nested_attributes_for :user
  belongs_to :order_status
  before_create :set_order_status
  before_save :update_subtotal

  # accepts_nested_attributes_for :user
  # accepts_nested_attributes_for :order_items
  # accepts_nested_attributes_for :bracelets
  #
  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
  def check_if_unless_one_color_is_unavailable
    self.bracelets.each do |bracelet|
      bracelet.colors.uniq.each do |color|
        if color.available == false
          return false
        end
      end
    end
    return true
  end
  
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to admin_order_path(@order), notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: admin_order_path(@order) }
      else
        format.html { render :new }
        format.json { render json: admin_order_path(@order).errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to admin_orders_path, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: admin_order_path(@order) }
      else
        format.html { render :edit }
        format.json { render json: admin_order_path(@order).errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:price, :subtotal, :tax, :shipping, :total, :order_status_id, :user_id, user_attributes: [:id, :first_name, :menu_id, :_destroy], order_items: [:id, :bracelet_id, :quantity, :_destroy])
    end
end

app/controllers/creator/orders_controller.rb
class Creator::OrdersController < Creator::CreatorController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order_items = @order.order_items
    @user = @order.user
  end
  
  def edit_shipping_address
    @user = User.find(params[:user_id])
  end
  def show_shipping_address
    @user = User.find(params[:user_id])
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to creator_order_path(@order), notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: creator_order_path(@order) }
      else
        format.html { render :new }
        format.json { render json: creator_order_path(@order).errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to creator_orders_path, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: creator_order_path(@order) }
      else
        format.html { render :edit }
        format.json { render json: creator_order_path(@order).errors, status: :unprocessable_entity }
      end
    end
    
    @order.bracelets.each do |b|
      if b.draft == true
        b.update(draft:false)
        b.save!
      end
    end
    
    if @order == current_order
      if current_order.order_status_id > 1
        session[:order_id] = nil
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to creator_orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:price, :subtotal, :tax, :shipping, :total, :order_status_id, :user_id, user_attributes:[:shipping_street_address, :shipping_zip, :shipping_city])
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:bracelet_id, :price)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.haml
= simple_nested_form_for [:admin, @order] do |f|
  - if @order.errors.any?
    #error_explanation
      %h2= "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      %ul
        - @order.errors.full_messages.each do |msg|
          %li= msg

  = f.association :user, :collection => User.order(:first_name), :prompt => 'Choose an existing owner'
  %br
  = f.association :bracelets, :collection => Bracelet.all, :prompt => 'bla'
  / Cena za jedną szt.
/   = number_to_currency order_item.unit_price
/   %br
/   Ilość
/   = order_item.quantity.to_i
/   %br
/   Cena łączna
/   %span{:style => "color: green"}= number_to_currency order_item.total_price
/   %br
/   %hr

app/views/admin/orders/_order_item_fields.html.slim
= f.simple_fields_for :order_item, OrderItem.new do |order_item|
	.nested-fields.component-fields
    = order_item.label "Podaj nazwę składnika:"
    = order_item.input :quantity, :label => false
    = order_item.label "Wybierz produkty dla składnika:"
    br
    br

app/views/admin/orders/edit.html.haml
%h1 Editing order

= render 'form'

= link_to 'Show', admin_order_path(@order)
\|
= link_to 'Back', :back

app/views/admin/orders/index.html.haml
%h1 Listing orders

%table
  %thead
    %tr
      %th Order id
      %th Price
      %th Status
      %th User id
      %th

  %tbody
    - @orders.each do |order|
      %tr
        %td= order.id
        %td= order.subtotal
        %td= order.order_status.name
        %td= order.user_id
        - if order.check_if_unless_one_color_is_unavailable == false
          %td
            = '!'
        - else
          %td
        %td= link_to 'Show', admin_order_path(order)
        %td= link_to 'Anuluj zamówienie', admin_order_path(order), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Order', new_admin_order_path

app/views/admin/orders/new.html.haml
%h1 New order

= render 'form'

= link_to 'Back', admin_orders_path

app/views/admin/orders/show.html.haml
%br
Łączna cena zamówienia:
%span{:style => "color: green"}= number_to_currency @order.subtotal
%br
= @order.order_status.name
%hr
%hr
- @order.order_items.each do |order_item|
  Bransoletka nr
  = order_item.bracelet.id.to_i
  = link_to 'zobacz', admin_bracelet_path(order_item.bracelet)
  %br
  Cena za jedną szt.
  = number_to_currency order_item.unit_price
  %br
  Ilość
  = order_item.quantity.to_i
  %br
  Cena łączna
  %span{:style => "color: green"}= number_to_currency order_item.total_price
  %br
  %hr
    