config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => { registrations: 'admin/registrations' }
  devise_for :users, :controllers => { registrations: 'creator/registrations' }
  
  get 'welcome/index'
  root 'welcome#index'

  namespace :admin do
    root to: 'dashboard#index'

    resource :dashboard
    resources :users
    resources :admins
    resources :orders
    resources :colors
    resources :collections
    resources :color_positions
    resources :bracelets do
      collection do
        get 'pallete'
        get 'change'
        get 'changerow'
        get 'changeentiretable'
      end
    end
  end

  namespace :creator do
    get 'order_items/create'
    get 'order_items/update'
    get 'order_items/destroy'
    get 'carts/show'
    post 'orders/change_order_status'
    resources :users
    resources :orders do
      collection do
        get 'show_shipping_address'
        get 'edit_shipping_address'
      end
    end
    resources :order_status
    resources :collections
    resources :colors, only: [:show, :index]
    resources :color_positions
    resources :order_items, only: [:create, :update, :destroy] do
      collection do
        get 'cart_row'
        get 'shopping_cart'
      end
    end
    resources :bracelets do
      member do
        get 'copy'
      end
      collection do
        get 'update_sum_price'
        get 'pallete'
        get 'change'
        get 'changerow'
        get 'changeentiretable'
        get 'draft_list'
      end
    end
  end

    

end

app/models/bracelet.rb
class Bracelet < ActiveRecord::Base
  has_many :color_positions
  has_many :order_items
  has_many :colors, through: :color_positions
  belongs_to :collection
  after_create :create_color_positions
  validates :height, :inclusion => { :in => 5..25, :message => "The height must be between 5 and 25" }
  validates :row_count, :inclusion => { :in => 5..15, :message => "The height must be between 5 and 15" }

  def create_color_positions
    a = (self.height * 4.55)
    z = [a, self.row_count].compact.inject(:*)
    y = z + (a * 0.5)
    (1..y).each do |x|
      colorPosition = ColorPosition.create(position: x, color_id: 1)
      colorPosition.bracelet = self
      colorPosition.save!
    end 
  end
  
  # def set_collection
  #     if self.collection.nil?
  #       self.collection = user.collection
  #     end
  # end

  def positions_in_first_look_for_iteration iteration
    row_width = row_count
    number_of_columns = (iteration % 2) == 0 ? row_width : row_width + 1

    idx = iteration * row_width +  (iteration)
    
    return self.color_positions.slice(idx, number_of_columns)
  
  end

  
  def rows_for_first_throw
    counter = 0
    (0..100).each do |i|
      if positions_in_first_look_for_iteration(i).blank?
        break
      else
        counter = counter + 1 
      end
    end

    return counter - 1
  end
  
  def positions_in_second_look_for_iteration iteration
    x = row_count % 2? row_count + 2 : rown_count + 1
    row_width = x * 0.5
    positions = positions_in_first_look_for_iteration(iteration)
    
    if !positions
      return nil
    end
    
    median = positions.count * 0.5
    
    from_idx = row_width * 0.5 - 1
    if iteration % 2 == 0
      from_idx = from_idx - 1
    end
    
    return positions.slice(from_idx, row_width)
  
  end
  
  def height_price
    height_price = 0
    if self.height <= 15
      height_price = -3
    end
    if self.height > 19
      height_price = 3
    end
    return height_price
  end
  
  def width_price
    width_price = 0
    if self.row_count >= 8
      width_price = 5
    end
    if self.row_count >= 10
      width_price = 10
    end
    if self.row_count >= 12
      width_price = 15
    end
    return width_price
  end
  
  def color_presence color
    return self.color_positions.where(color: color).count
  end
  
  def dominate_colors
    result = []
    self.colors.uniq.each do |color|
    
      if self.color_presence(color) > 10
        result.push(color)
      end
    end
    
    return result
  end
  
  def color_price
    color_price = 0
    if self.dominate_colors.count >=2
      color_price = 2
    end
    if self.dominate_colors.count > 3
      color_price = 5
    end
    if self.dominate_colors.count > 5
      color_price = 7
    end
    return color_price
  end
  
  def sum_price
    self.price = 25
    return self.price + color_price + height_price + width_price
  end
  
  
  def find_unavailable_colors
    result = []
    self.colors.uniq.each do |color|
      if color.available == false
        result.push("Kolor #{color.name} przestał być dostępny")
      end
    end
    return result
  end
  
  def pattern
    result = Hash.new
    index = 0
    counter = 0
    hash_position = 0
    current_color = self.color_positions.first.color
    self.color_positions.each do |cp|
      if cp.color == current_color
        counter = counter + 1
      end
      index = index + 1
      next_position = self.color_positions[index]
      if !next_position.present? || next_position.color != current_color 
        result[hash_position]= {'color' => current_color, 'count' => counter}
        counter = 0
        hash_position = hash_position + 1
        if next_position.present?
          current_color = next_position.color
        end
      end
    end
    
    return result
  end

  private
    def default_values
      self.draft ||= true
    end
end

app/controllers/admin/bracelets_controller.rb
class Admin::BraceletsController < Admin::AdminController
  before_action :set_bracelet, only: [:show, :edit, :update, :destroy, :changerow, :changeentiretable]
  before_action :set_current_color, only: [:pallete, :edit, :change, :changerow, :changeentiretable]
  before_action :set_color_position, only: [:change]
  # GET /bracelets
  # GET /bracelets.json
  
  
  def index
    @bracelets = Bracelet.all
  end

  # GET /bracelets/1
  # GET /bracelets/1.json
  def show
    @color_positions = @bracelet.color_positions
    @colors = @bracelet.colors.uniq
  end

  # GET /bracelets/new 
  def new
    @bracelet = Bracelet.new
  end

  def pallete
    @colors = Color.available
  end

  def change
    @color_position.color = @current_color
    @color_position.save!
  end

  def changerow
    @row_index = params[:row_idx].to_i
    
    @color_positions = @bracelet.positions_in_first_look_for_iteration(@row_index)
    
    @color_positions.each do |color_position|
      color_position.color = @current_color
      color_position.save
    end
  end
  
  def changeentiretable
    @bracelet.color_positions.each do |cp|
      cp.color = @current_color
      cp.save
    end
  end
  
  # GET /bracelets/1/edit
  
  def edit
    @colors = Color.all
  end

  # POST /bracelets
  # POST /bracelets.json
  
  def create
    @users = User.all
    @bracelet = Bracelet.new(bracelet_params)
    respond_to do |format|
      if @bracelet.save
        format.html { redirect_to edit_admin_bracelet_path(@bracelet), notice: 'Bracelet was successfully created.' }
        format.json { render :edit, status: :created, location: admin_bracelet_path(@bracelet) }
      else
        format.html { render :new }
        format.json { render json: admin_bracelet_path(@bracelet).errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bracelets/1
  # PATCH/PUT /bracelets/1.json
  
  def update
    if @bracelet.colors.uniq.count > 7
      redirect_to edit_creator_bracelet_path(@bracelet), notice: 'Użyłeś za dużo kolorów. Maksymalna ilość kolorów w bransoletce to 7'
      return
    end
      respond_to do |format|
        if @bracelet.update(bracelet_params)
          format.html { redirect_to admin_bracelet_path(@bracelet), notice: 'Bracelet was successfully updated.' }
          format.json { render :show, status: :ok, location: admin_bracelet_path(@bracelet) }
        else
          format.html { render :edit }
          format.json { render json: admin_bracelet_path(@bracelet).errors, status: :unprocessable_entity }
        end
      end
    end

  # DELETE /bracelets/1
  # DELETE /bracelets/1.json
  def destroy
    @bracelet.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Bracelet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_color_position
      @color_position = ColorPosition.find(params[:position_id])
    end

    def set_current_color
      @current_color = Color.find_by_hex(params[:current_color].upcase) if params[:current_color]
      
      if !@current_color
          @current_color = Color.first
      end
    end

    def set_bracelet
      @bracelet = Bracelet.includes(:color_positions => [:color]).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bracelet_params
      params.require(:bracelet).permit(:clasp, :casp, :color_position_id, :row_count, :price, :height, :draft, :collection_id)
    end
end

app/controllers/bracelets_controller.rb
class BraceletsController < ApplicationController
  before_action :set_bracelet, only: [:show, :edit, :update, :destroy]
  before_action :set_current_color, only: [:pallete, :edit, :change]
  before_action :set_color_position, only: [:change]
  # GET /bracelets
  # GET /bracelets.json
  
  
  def index
    @bracelets = Bracelet.all
  end

  # GET /bracelets/1
  # GET /bracelets/1.json
  def show
  end

  # GET /bracelets/new
  def new
    @bracelet = Bracelet.new
  end

  def pallete
    @colors = Color.all
  end

  def change
    @color_position.color = @current_color
    @color_position.save!
  end

  # GET /bracelets/1/edit
  def edit
    @colors = Color.all
  end

  # POST /bracelets
  # POST /bracelets.json
  def create
    @bracelet = Bracelet.new(bracelet_params)
    respond_to do |format|
      if @bracelet.save
        format.html { redirect_to edit_bracelet_path(@bracelet), notice: 'Bracelet was successfully created.' }
        format.json { render :edit, status: :created, location: @bracelet }
      else
        format.html { render :new }
        format.json { render json: @bracelet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bracelets/1
  # PATCH/PUT /bracelets/1.json
  def update
    respond_to do |format|
      if @bracelet.update(bracelet_params)
        format.html { redirect_to @bracelet, notice: 'Bracelet was successfully updated.' }
        format.json { render :show, status: :ok, location: @bracelet }
      else
        format.html { render :edit }
        format.json { render json: @bracelet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bracelets/1
  # DELETE /bracelets/1.json
  def destroy
    @bracelet.destroy
    respond_to do |format|
      format.html { redirect_to bracelets_url, notice: 'Bracelet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_color_position
      @color_position = ColorPosition.find(params[:position_id])
    end

    def set_current_color
      @current_color = Color.find_by_hex(params[:current_color].upcase) if params[:current_color]
      
      if !@current_color
          @current_color = Color.first
      end

    end

    def set_bracelet
      @bracelet = Bracelet.includes(:color_positions).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bracelet_params
      params.require(:bracelet).permit(:clasp, :casp, :color_position_id, :row_count, :price, :height)
    end
end

app/controllers/creator/bracelets_controller.rb
class Creator::BraceletsController < Creator::CreatorController
  before_action :set_bracelet, only: [:show, :edit, :update, :destroy, :changerow, :changeentiretable]
  before_action :set_current_color, only: [:pallete, :edit, :change, :changerow, :changeentiretable, :copy]
  before_action :set_color_position, only: [:change]
  # GET /bracelets
  # GET /bracelets.json
  
  
  def index
    @bracelets = Bracelet.where(collection_id: current_user.collection.id)
    @order_item = current_order.order_items.new
  end
  
  # GET /bracelets/1
  # GET /bracelets/1.json
  def show
    @colors = @bracelet.colors.uniq
  end
  
  def copy
    @colors = Color.available
    @old_bracelet = Bracelet.find(params[:id])
    @bracelet = @old_bracelet.deep_clone include: :color_positions
    @bracelet.collection = Collection.find_by(user_id: current_user.id)
    @bracelet.save!
    render 'edit'
  end

  # GET /bracelets/new
  def new
    @bracelet = Bracelet.new
  end

  def pallete
    @colors = Color.available
  end

  def change
    @color_position.color = @current_color
    @color_position.save!
  end

  def changerow

    @row_index = params[:row_idx].to_i
    
    @color_positions = @bracelet.positions_in_first_look_for_iteration(@row_index)
    
    @color_positions.each do |color_position|
      color_position.color = @current_color
      color_position.save
    end

  end
  
  def changeentiretable
    
    @bracelet.color_positions.each do |cp|
      cp.color = @current_color
      cp.save
    end
    
  end
  def update_sum_price
    @bracelet = Bracelet.find(params[:bracelet_id])
  end
  # GET /bracelets/1/edit
  def edit
    @colors = Color.available
  end

  # POST /bracelets
  # POST /bracelets.json
  def create
    params[:bracelet][:user_id]= current_user.id   
    @bracelet = Bracelet.new(bracelet_params)
    respond_to do |format|
      if @bracelet.save
        format.html { redirect_to edit_creator_bracelet_path(@bracelet), notice: 'Bracelet was successfully created.' }
        format.json { render :edit, status: :created, location: creator_bracelet_path(@bracelet) }
      else
        format.html { render :new }
        format.json { render json: creator_bracelet_path(@bracelet).errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bracelets/1
  # PATCH/PUT /bracelets/1.json
  def update
      respond_to do |format|
        if @bracelet.update(bracelet_params)
          format.html { redirect_to creator_bracelet_path(@bracelet), notice: 'Bracelet was successfully updated.' }
          format.json { render :show, status: :ok, location: admin_bracelet_path(@bracelet) }
        else
          format.html { render :edit }
          format.json { render json: creator_bracelet_path(@bracelet).errors, status: :unprocessable_entity }
        end
      end
  end

  # DELETE /bracelets/1
  # DELETE /bracelets/1.json
  def destroy
    @bracelet.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Bracelet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_color_position
      @color_position = ColorPosition.find(params[:position_id])
    end

    def set_current_color
      @current_color = Color.find_by_hex(params[:current_color].upcase) if params[:current_color]
      
      if !@current_color
          @current_color = Color.first
      end

    end

    def set_bracelet
      @bracelet = Bracelet.includes(:color_positions => [:color]).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bracelet_params
      params.require(:bracelet).permit(:clasp, :casp, :color_position_id, :row_count, :price, :height, :draft, :collection_id)
    end
end

app/helpers/bracelets_helper.rb
module BraceletsHelper
end

app/views/admin/bracelets/_draft_list.html.haml
%h1 Moje bransoletki

%table
  %thead
    %tr
      %th Id
      %th Zakończenie
      %th Zapięcie
      %th Grubość
      %th Długość
      %th Zamówiona
      %th Cena
      %th
      %th

  %tbody
        %td= bracelet.id
        %td= bracelet.clasp
        %td= bracelet.casp
        %td= bracelet.row_count
        %td= bracelet.height
        %td
          - if bracelet.draft == true
            = 'Nie'
          - else
            = 'Tak'
        %td= number_to_currency bracelet.sum_price
        %td= link_to 'Edit', edit_creator_bracelet_path(bracelet)
        %td= render "bracelet_row", bracelet: bracelet, order_item: @order_item

app/views/admin/bracelets/_editform.html.haml
= simple_form_for [:admin, @bracelet] do |f|
  = notice
  - if @bracelet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bracelet.errors.count, "error")} prohibited this bracelet from being saved:"
      %ul
        - @bracelet.errors.full_messages.each do |msg|
          %li= msg
  %br
  %br
  = '1. Wybierz kolor'
  %br
  = '2. Wypełnij wszystko klikając na przycisk "wypełnij"(może to potrwać chwilę), wypełnij poszczególne wiersze klikając na ikonki lub wypełnij poszczególne komórki klikając na komórki'
  %br
  = '3. Stwórz swój wzór. Jeśli chcesz powtarzalny schemat na bransoletce wykonaj jeden schemat, resztę wzoru pozostaw białym.'
  %br
  = '4. Obserwuj zmiany na symulatorze bransoletki'
  %br
  = '5. Wybierz końcówki i zapięcie'
  %br
  = '6. Podsumuj swój projekt'
  %br
  %br
  = 'Twoja początkowa cena dla wybranej długości i szerokości bransoletki to:'
  %br
  = 'Cena netto'
  = number_to_currency(@bracelet.sum_price)
  = 'Cena brutto'
  = number_to_currency(@bracelet.sum_price * 1.23)
  %br
  = "Jeśli chcesz zmienić długość i szerokość bransoletki zrób to zanim stworzysz wzór! Jeśli się cofniesz, wszystkie zmiany z tego widoku nie zostaną zapisane."
  = link_to 'Zmień długość i szerokość bransoletki', new_admin_bracelet_path
  %br
  %br
  = render 'pallete' 
  %table
    %tr
      %td{class: "fill-entire_table", style:'width:150px',onclick:"adfillTable(#{@bracelet.id})"}
        %center
          = "wypełnij"
  = render 'first_throw'
  .tools{style:'margin-left:15px;display:table;float:left'}
    - a = @bracelet.rows_for_first_throw
    - (0..a).each do |row_index|
      %table
        %tr
          %td{class: "fill-row-#{row_index}", style:'background-image:url("/assets/stock_bucketfill.png");background-size:cover', onclick:"adfillRow(#{row_index}, #{@bracelet.id})"}


  = render 'second_throw'
  .field
    = f.input :casp, label: "Wybierz kolor wykończenia bransoletki", collection: ["Srebrne","Złote","Miedziane"]
  .field
    = f.input :clasp, label: "Wybierz zapięcie", collection: ["karabińczyk","toogle"]
  = 'Cena netto'
  = number_to_currency(@bracelet.sum_price)
  = 'Cena brutto'
  = number_to_currency(@bracelet.sum_price * 1.23)
  %br
  = f.input :collection_id, collection: Collection.all
  %button 
    = link_to "Przelicz cenę", edit_admin_bracelet_path(@bracelet), :method => :get
  %br
  .actions
    = f.submit 'Zapisz i złóż zamówienie później'
    / = link_to 'Złóż zamówienie'

app/views/admin/bracelets/_first_throw.html.haml
#entire_table{style:'margin-left:5px;display:table;float:left'}
  - a = (@bracelet.height * 4.55).ceil
  - (0..a).each do |row_index|
    %table
      = render 'single_row', :@color_positions => @bracelet.positions_in_first_look_for_iteration(row_index).to_a, :@row_index => row_index

app/views/admin/bracelets/_form.html.haml
= simple_form_for [:admin, @bracelet] do |f|
  - if @bracelet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bracelet.errors.count, "error")} prohibited this bracelet from being saved:"
      %ul
        - @bracelet.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :row_count
    = f.number_field :row_count
  .field
    = f.label :height
    = f.number_field :height
  .field
    = f.label "Wybierz Użytkownika"
    %br/
  .actions
    = f.submit 'Save'

app/views/admin/bracelets/_pallete.html.haml
#pallete-full
  #current-color{style: "width: 20px; height: 20px; background-color:##{@current_color.hex};border: 1px solid black;"}
  %table
    - @colors.each do |color|
      %tr
        %td
          = color.try(:name)
        %td.color-to-select{style:"background-color:##{color.hex}", :onclick => "adsetAsSelectedColor()"}

app/views/admin/bracelets/_second_throw.html.haml
#entire_table_second{style:'margin-left:15px;float:left'}
  - a = (@bracelet.height * 4.55).ceil
  - (0..a).each do |row_index|
    %table
      = render 'single_row_second_throw', :@color_positions => @bracelet.positions_in_second_look_for_iteration(row_index).to_a, :@row_index => row_index

app/views/admin/bracelets/_single_row.html.haml
%tr{id: "cp-single-row-#{@row_index}"}
  - if ((@row_index % 2 ) == 0)
    %td{class:"no-border"}
  - @color_positions.each do |x|
    %td{onclick:"adchangeColor(#{x.id})", id: "cp-#{x.id}", style:"background-color:##{x.color.hex};", class: "cp-row-#{@row_index}"}
      - x.position

app/views/admin/bracelets/_single_row_second_throw.html.haml
%tr{id: "cp-single-row-#{@row_index}"}
  - if ((@row_index % 2 ) == 0)
    - can = @color_positions.first
  - else
    - can = @color_positions.last
  - @color_positions.each do |x|
    - cla = can == x ? 'small' : 'normal'
    %td{onclick:"adchangeColor(#{x.id})", id: "cp-#{x.id}", style:"background-color:##{x.color.hex};", class: "cp-row-#{@row_index} #{cla}"}
      - x.position

app/views/admin/bracelets/_single_table.html.haml
%tr{id: "cp-single-table-#{@entire_table}"}
  - if ((@entire_table % 2 ) == 0)
    %td{class:"no-border"}
  - @color_positions.each do |x|
    %td{onclick:"adchangeColor(#{x.id})", id: "cp-#{x.id}", style:"background-color:##{x.color.hex};", class: "cp-row-#{@entire_table}"}
      - x.position

app/views/admin/bracelets/edit.html.haml
%h1 Editing bracelet

= render 'editform'

app/views/admin/bracelets/index.html.haml
/ %h1 Bransoletki zamówione
/ %table
/   %thead
/     %tr
/       %th Clasp
/       %th Casp
/       %th Row count
/       %th Height
/       %th Price
/       %th order
/       %th
/       %th
/       %th
/     %tbody
/     - @bracelets.each do |bracelet|
/       %tr
/         %td= bracelet.clasp
/         %td= bracelet.casp
/         %td= bracelet.row_count
/         %td= bracelet.height
/         %td= bracelet.price
/         %td= bracelet.order.id.to_s
/         %td= link_to 'Show', admin_bracelet_path(bracelet)
/         %td= link_to 'Edit', edit_admin_bracelet_path(bracelet)
/         %td= link_to 'Destroy', admin_bracelet_path(bracelet), :method => :delete, :data => { :confirm => 'Are you sure?' }
%h1 Bransoletki niezamówione
%table
  %thead
    %tr
      %th ID
      %th Clasp
      %th Casp
      %th Row count
      %th Height
      %th Price
      %th
      %th
      %th
    %tbody
    - @bracelets.each do |bracelet|
      %tr
        %td= bracelet.id
        %td= bracelet.clasp
        %td= bracelet.casp
        %td= bracelet.row_count
        %td= bracelet.height
        %td= bracelet.sum_price
        %td= link_to 'Show', admin_bracelet_path(bracelet)
        %td= link_to 'Edit', edit_admin_bracelet_path(bracelet)
        %td= link_to 'Destroy', admin_bracelet_path(bracelet), :method => :delete, :data => { :confirm => 'Are you sure?' }
%br
= link_to 'New Bracelet', new_admin_bracelet_path

app/views/admin/bracelets/new.html.haml
%h1 New bracelet

= render 'form'

= link_to 'Back', :back

app/views/admin/bracelets/show.html.haml
%p#notice= notice
#printable
  %button{:onclick => "PrintDiv('printable','filename');return false;", class:'hidden-on-print'}
    = "Drukuj"
  %br
  Kolory użyte w bransoletce:
  = @colors.count
  %table
    - @colors.each do |color|
      %tr
        %td
          = color.try(:name)
        %td.color-to-select{style:"background-color:##{color.hex}"}
  %table
    - hash = @bracelet.pattern
    - hash.keys.sort.each do |key|
      - value = hash[key]
      %tr
        %td.admin-small{style:"background-color:##{value['color'].hex};"}
        %td 
          = "#{value['color'].name}"
        %td
          = "#{value['count']}"
    / %table
/       - @bracelet.color_positions.in_groups_of(50,false) do |row|
/         %tr
/           - row.each do |x|
/             %td.admin-small{style:"background-color:##{x.color.hex};"}
/               - x.position
.panel
  .div-right          
    %br
    Zapięcie:
    = @bracelet.clasp
    %br
    Wykończenie:
    = @bracelet.casp
    %br
    Ilość koralików w rzędzie
    = @bracelet.row_count
    %br
    Długość bransoletki
    = @bracelet.height.to_s + ' cm'
    %br
    = 'Cena netto'
    = number_to_currency(@bracelet.sum_price)
    %br
    = 'Cena brutto'
    = number_to_currency(@bracelet.sum_price * 1.23)
    %br
    = link_to 'Edit', edit_admin_bracelet_path(@bracelet)
    \|
    = link_to 'Back', :back
    %br
    = 'Podgląd wzoru'
  %div{:style => "transform:rotate(90deg); -webkit-transform:rotate(90deg); \r\n-moz-transform:rotate(90deg); -o-transform:rotate(90deg);display: inline-block;margin-left:40%;margin-top:-30%"}
    - a = (@bracelet.height * 4.55).ceil
    - (0..a).each do |row_index|
      %table
        %tr
          - if ((row_index % 2 ) == 0)
            %td.small-no-border
          - @bracelet.positions_in_first_look_for_iteration(row_index).to_a.each do |x|
            %td.small{style:"background-color:##{x.color.hex};"}
              - x.position
  %br
  %div{:style => "transform:rotate(90deg); -webkit-transform:rotate(90deg); \r\n-moz-transform:rotate(90deg); -o-transform:rotate(90deg);display: inline-block;margin-left:42%;margin-top:-60%"}
    - a = (@bracelet.height * 4.55).ceil
    - (0..a).each do |row_index|
      %table
        %tr
          - if ((row_index % 2 ) == 0)
            - can = @bracelet.positions_in_second_look_for_iteration(row_index).to_a.first
          - else
            - can = @bracelet.positions_in_second_look_for_iteration(row_index).to_a.last  
          - @bracelet.positions_in_second_look_for_iteration(row_index).to_a.each do |x|
            - cla = can == x ? 'small_second' : 'normal_second'
            %td{style:"background-color:##{x.color.hex};", class: "#{cla}"}
              - x.position