config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => { registrations: 'admin/registrations' }
  devise_for :users, :controllers => { registrations: 'creator/registrations' }
  
  get 'welcome/index'
  root 'welcome#index'

  namespace :admin do
    root to: 'dashboard#index'

    resource :dashboard
    resources :users
    resources :admins
    resources :orders
    resources :colors
    resources :collections
    resources :color_positions
    resources :bracelets do
      collection do
        get 'pallete'
        get 'change'
        get 'changerow'
        get 'changeentiretable'
      end
    end
  end

  namespace :creator do
    get 'order_items/create'
    get 'order_items/update'
    get 'order_items/destroy'
    get 'carts/show'
    post 'orders/change_order_status'
    resources :users
    resources :orders do
      collection do
        get 'show_shipping_address'
        get 'edit_shipping_address'
      end
    end
    resources :order_status
    resources :collections
    resources :colors, only: [:show, :index]
    resources :color_positions
    resources :order_items, only: [:create, :update, :destroy] do
      collection do
        get 'cart_row'
        get 'shopping_cart'
      end
    end
    resources :bracelets do
      member do
        get 'copy'
      end
      collection do
        get 'update_sum_price'
        get 'pallete'
        get 'change'
        get 'changerow'
        get 'changeentiretable'
        get 'draft_list'
      end
    end
  end

    

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :bracelets
  belongs_to :user
end

app/controllers/admin/collections_controller.rb
class Admin::CollectionsController < Admin::AdminController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @bracelets = @collection.bracelets
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:bracelet_id, :user_id)
    end
end

app/controllers/creator/collections_controller.rb
class  Creator::CollectionsController < Creator::CreatorController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @public_collections = Collection.where(public: true)
    @my_collection = Collection.where(user_id: current_user)
    @collections = @public_collections.to_a + @my_collection.to_a
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @bracelets = @collection.bracelets
    @order_item = current_order.order_items.new
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end


  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:user_id)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/admin/collections/_form.html.haml
= form_for [:admin, @collection] do |f|
  .form-inputs
    = f.input :bracelet_id
    = f.input :user_id
  .form-actions
    = f.button :submit

app/views/admin/collections/edit.html.haml
%h1 Editing collection

= render 'form'

= link_to 'Show', @collection
\|
= link_to 'Back', collections_path

app/views/admin/collections/index.html.haml
%h1 Listing collections

%table
  %thead
    %tr
      %th Imię
      %th Nazwisko
      %th Nazwa kolekcji
      %th Public
      %th
      %th

  %tbody
    - @collections.each do |collection|
      %tr
        %td= collection.user.first_name if collection.user.present?
        %td= collection.user.last_name if collection.user.present?
        %td= collection.name
        %td= collection.public
        %td= link_to 'Show', admin_collection_path(collection)
        %td= link_to 'Edit', edit_admin_collection_path(collection)
        %td= link_to 'Destroy', admin_collection_path(collection), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Collection', new_admin_collection_path

app/views/admin/collections/new.html.haml
%h1 New collection

= render 'form'

= link_to 'Back', collections_path

app/views/admin/collections/show.html.haml
%p#notice= notice

%p
  %b Bracelet:
  - @bracelets.each do |bracelet|
    %br
    = bracelet.id
    = link_to 'Usuń bransoletkę', admin_bracelet_path(bracelet), :method => :delete, :data => { :confirm => 'Are you sure?' }

= link_to 'Edit', edit_admin_collection_path(@collection)
\|
= link_to 'Back', admin_collections_path